version: "3.8"
   
services:
  web:
    image: eecs4314prismbreak/wheypal:latest
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - REDIS=redis:6379
    depends_on:
      - redis
    #   - db
  redis:
    image: redis:6.0.6-alpine
    command: redis-server
    ports:
      - 6379:6379
  # frontend:
  #     image: eecs4314prismbreak/wheypal-frontend:latest
  #     ports:
  #       - "80:80"
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres